image: Visual Studio 2017
install:
  - choco install gitversion.portable -y

before_build:
  - cmd: dotnet --version
  - ps: gitversion /l console /output buildserver

build_script:
  - ps: dotnet msbuild /t:Restore /t:Build /p:Configuration=Release /p:Version=$env:GitVersion_NuGetVersion src/
  
test_script:
  - ps: dotnet test --configuration Release --no-build $(Resolve-Path ".\src\*.UnitTests\*.csproj")

artifacts:
- path: artifacts/*/*.nupkg

deploy:
  provider: NuGet
  api_key:
    secure: GlvYAKY5JPJ14S02RIREv8XBDz/Uu3I2QwSTQjzu2dJB9zp3d+OSQgo0IBqI8z0j
  on:
    appveyor_repo_tag: true